project:
  type: default
  pre-render: python generate_figures.py
  render:
    - template-computo-python.qmd
    - README.qmd

title: "Optimal sub-Gaussian constants for discrete noise models in learning"
author:
  - name: Soufiane Atouani
    corresponding: true
    email: soufiane.atouani@inria.fr
    affiliations:
      - name: Université Grenoble Alpes, Inria, CNRS, Grenoble INP, LJK, 38000 Grenoble, France
        #department: Laboratoire Jean Kuntzmann
        url: https://www-ljk.imag.fr/
  - name: Olivier Marchal
    email: olivier.marchal@univ-st-etienne.fr
    url: https://math.univ-lyon1.fr/~marchal/index.html
    affiliations:
      - name: Université Jean Monnet Saint-Étienne, CNRS, Institut Camille Jordan UMR 5208
      - name: Institut Universitaire de France, Les Forges 2, 20 Rue du Dr Annino, 42000 Saint-Étienne, France
        #department: Institut Camille Jordan
        url: https://math.univ-lyon1.fr/icj/
  - name: Julyan Arbel 
    email: julyan.arbel@inria.fr
    url: https://www.julyanarbel.com/
    affiliations:
      - name: Université Grenoble Alpes, Inria, CNRS, Grenoble INP, LJK, 38000 Grenoble, France
        #department: Laboratoire Jean Kuntzmann
        url: https://www-ljk.imag.fr/
date: 17-01-2026
date-modified: last-modified
# description: |
#   Template for preparing a submission to Computo, using the [quarto journal extension](https://github.com/computorg/computo-quarto-extension), the Jupyter kernel (Python user) and the environment files to set-up the dependencies.

#   For a detailed, step-by-step guide on preparing your article, setting up the continuous integration and submitting it to Computo, please consult the [guidelines for authors](https://computo-journal.org/site/guidelines-authors.html).
abstract: >+
  Sub-Gaussian assumptions are a cornerstone of learning theory, underpinning concentration
  inequalities, generalization bounds, and regret analyses in online learning and bandit problems.
  While such results crucially depend on sub-Gaussian constants, these parameters are often chosen
  conservatively, overlooking the fine structure of the underlying noise distribution.
  In this work, we characterize optimal sub-Gaussian variance proxies for a class of discrete
  random variables with equally spaced support. We develop a general framework that
  yields a practical procedure to compute optimal variance proxies from the moment-generating
  function. As a first application, we provide a complete analysis of three-point distributions,
  thereby extending the classical Bernoulli case. We uncover sharp phase transitions between
  strict and non-strict sub-Gaussian regimes and derive explicit expressions for the optimal
  variance proxy in both symmetric and asymmetric settings. We further show that the discrete
  uniform distribution on $N$ points is strictly sub-Gaussian for all $N \geq 2$.
  Building on these characterizations, we demonstrate how optimal variance proxies can be
  plugged into standard concentration inequalities and stochastic bandit analyses, leading to
  tighter confidence bounds and improved constants in regret guarantees without modifying the
  underlying algorithms. Finally, we provide an open-source Python package that implements our
  theoretical results and enables the computation of optimal sub-Gaussian variance proxies for a
  wide range of distributions.
keywords: [Sub-Gaussian property, discrete distributions, Uniform distribution, bandits]
bibliography: references.bib
github-user: satouani
repo: "Sub-Gaussian-Proxy-Variance-Library.git"
draft: false # set to false once the build is running
published: false # will be set to true once accepted
license: CC-BY-4.0
format:
  computo-html: default
  computo-pdf: default
          
        

jupyter: python3
